# Autogenerated wrapper script for gsasl_jll for x86_64-w64-mingw32
export gsasl, libgsasl

JLLWrappers.@generate_wrapper_header("gsasl")
JLLWrappers.@declare_executable_product(gsasl)
JLLWrappers.@declare_library_product(libgsasl, "libgsasl-18.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        gsasl,
        "bin\\gsasl.exe",
    )

    JLLWrappers.@init_library_product(
        libgsasl,
        "bin\\libgsasl-18.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
